apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackaton-iadt-deployment
  namespace: iadt
  labels:
    app: hackaton-iadt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackaton-iadt
  template:
    metadata:
      labels:
        app: hackaton-iadt
    spec:
      containers:
        - name: hackaton-iadt
          image: hackaton-iadt:latest
          ports:
            - containerPort: 8000
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: iadt-secrets
                  key: gemini_api_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: iadt-secrets
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: iadt-secrets
                  key: aws_secret_access_key
            - name: AWS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: iadt-secrets
                  key: aws_region_name
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: iadt-secrets
                  key: api_key
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always


