apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hackaton-iadt-data-pvc
  namespace: iadt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv
